# Generated by Django 6.0.1 on 2026-02-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
