# Generated by Django 6.0.1 on 2026-02-24 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_remove_shopprofile_phone_alter_shopprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='customer_mobile',
            new_name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
