# Generated by Django 6.0.1 on 2026-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_rename_customer_mobile_bill_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='amount',
        ),
        migrations.AlterField(
            model_name='billitem',
            name='hsn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
