# Generated by Django 6.0.1 on 2026-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_remove_billitem_amount_alter_billitem_hsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
