# Generated by Django 6.0.1 on 2026-02-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0005_shopprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
