# Generated by Django 6.0.1 on 2026-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0006_alter_bill_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
