# Generated by Django 6.0.1 on 2026-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0007_bill_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
