# Generated by Django 6.0.1 on 2026-02-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0008_bill_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=20),
        ),
    ]
